name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  test:
    strategy:
      matrix:
        webrpc-gen: [v0.7.0]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Install webrpc-gen
        #run: go install github.com/webrpc/webrpc/cmd/gen@${{ matrix.webrpc-gen }}
        run: |
          git clone --single-branch https://github.com/golang-cz/webrpc.git --branch gen_v2_templates_api
          cd webrpc
          make install
      - name: Regenerate example schema
        run: webrpc-gen -schema=./_examples/example.ridl -target=. -out=./_examples/example.openapi.gen.yaml
      - name: Git diff of regenerated files
        run: git diff --color --ignore-all-space --ignore-blank-lines --exit-code
